### ISSUE TITLE
Todo cleanup?

### ISSUE THREAD

**Issue by danmarsden** [ndunand/moodle-availability_useragent#4]
https://github.com/ndunand/moodle-availability_useragent/blob/399018da7d5aeeceb3b2ada46e19bdfcab851428/classes/condition.php#L118

You might have already solved the todo?

**Comment by danmarsden** [comment]
Another one,?

https://github.com/ndunand/moodle-availability_useragent/blob/399018da7d5aeeceb3b2ada46e19bdfcab851428/lang/en/availability_useragent.php#L30

**Comment by ndunand** [comment]
Thanks, sorry for overlooking this. Removed in 0effe67d57bbed86a67 .

**Comment by danmarsden** [comment]
Haha don't say sorry! I was getting very picky! I hate to think how much dust I've left in my own code! :-)

**Comment by ndunand** [comment]
😊 well, thanks for taking the time to go through this. It's a very simple plugin so little code but in the hope it'd be useful to others I thought I'd try and get it published.
